# Generated by Django 2.2.7 on 2020-06-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(help_text='account', max_length=50)),
                ('password', models.CharField(help_text='password', max_length=50)),
            ],
        ),
    ]
