# Generated by Django 3.0.7 on 2020-06-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gossip', '0002_auto_20200625_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('topic', models.CharField(help_text='topic', max_length=100)),
            ],
        ),
    ]
